version: "3.8"

services:
  freelance_web:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    container_name: edu_exams
    command: /scripts/run_django.sh
    env_file:
      - .env
    volumes:
      - .:/project
    ports:
      - "8001:8000"
      - "81:80"
    depends_on:
      - edu_exams_db

  freelance_db:
    image: postgres
    volumes:
      - freelance_volume:/var/lib/postgresql/data/
    ports:
      - "5442:5432"
    env_file:
      - .env

volumes:
  freelance_volume:
