version: "3.8"

services:
  edu_exams_db:
    image: postgres
    volumes:
      - freelance_volume:/var/lib/postgresql/data/
    ports:
      - "5442:5432"
    env_file:
      - .env

volumes:
  freelance_volume:
