# Generated by Django 4.0.6 on 2023-05-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertags',
            name='order',
        ),
        migrations.RemoveField(
            model_name='ordertags',
            name='tag',
        ),
        migrations.AddField(
            model_name='order',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='orders.category'),
        ),
        migrations.AddField(
            model_name='order',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='orders.tag'),
        ),
        migrations.DeleteModel(
            name='OrderCategory',
        ),
        migrations.DeleteModel(
            name='OrderTags',
        ),
    ]
