# Generated by Django 4.0.6 on 2023-05-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_done',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_employee_selected',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
