# Generated by Django 4.0.6 on 2023-05-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_datetime_compelete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderresponse',
            name='is_seen',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
